CREATE TABLE IF NOT EXISTS item (
  ITEM_ID         INTEGER,
  ITEM_NAME VARCHAR(30) NOT NULL,
  ITEM_DESC  VARCHAR(50) NOT NULL,
  PRIMARY KEY (ITEM_ID)
);

CREATE TABLE IF NOT EXISTS picture (
  PIC_ID         INTEGER,
  PIC_NAME VARCHAR(30) NOT NULL,
  PIC_DATA  BLOB,
  ITEM_ID         INTEGER NOT NULL,
  PRIMARY KEY (PIC_ID),
  FOREIGN KEY (ITEM_ID) 
  REFERENCES item(ITEM_ID)
);
